#!/usr/local/bin/php
<?php
require('db_settings.inc');

/**
 * Development dump filters data that doesn't need to be stored within version 
 * control and changes certain tables to not be dropped so their data will be 
 * preserved in the developer's MySQL.
 */

foreach($tables_filtered_dev as $filtered_data) {
  $filter .= "|grep -v 'INSERT INTO .".$filtered_data.".' ";
}

foreach($tables_preserved_dev as $preserved_data) {
  $filter .= "|grep -v 'DROP TABLE IF EXISTS .".$preserved_data.".;' |sed 's/CREATE TABLE .".$preserved_data.". (/CREATE TABLE IF NOT EXISTS `".$preserved_data."` (/g' |grep -v 'INSERT INTO .".$preserved_data.". VALUES' ";
}

$dump_options = "--skip-opt --add-drop-table --add-locks --create-options --quick --lock-tables --set-charset --disable-keys --order-by-primary --comments=FALSE --default-character-set=utf8 --hex-blob";

exec("mysqldump $dump_options $db_connection_settings $filter > ".$path."dbscripts/databases/development.sql");

print("Dump complete.\n");