#!/usr/local/bin/php
<?php
require('db_settings.inc');

if (option('help')) {
  echo <<<EOF

Perform a database dump.

Usage: {$script_path}dump_database [OPTIONS]
Example: {$script_path}dump_database --prod --min

All arguments are long options.

  --help       This page.

  --dev        Dump the database to the development dump file.  This is the default option.

  --prod       Dump the database to the production dump file.

  --lastmerge  Dump the database to the last-merge dump file.

  --full       Filter the output using the full options (as set in the config.inc file).  This is the default option.

  --min        Filter the output using the minimal options (as set in the config.inc file).

  --none       Do not perform any filtering, and dump the full database.

\n
EOF;
  exit;
}


// Set file to be dumped to
if (option('prod')) {
  $file = 'production.sql';
} elseif (option('lastmerge')) {
  $file = 'last-merge.sql';
} else {
  $file = 'development.sql';
}

if (option('none')) {
  $filter_mode = 'none';
} elseif (option('min')) {
  $filter_mode = 'min';
}

switch($filter_mode){
  case 'none':
    $filter = '';
    $message = "Performed a full database dump to $file.";
    break;

  case 'min':
    foreach($tables_filtered as $filtered_data) {
      $filter .= "|grep -v 'INSERT INTO .".$filtered_data.".' ";
    }
    foreach($tables_preserved_min as $preserved_data) {
      $filter .= "|grep -v 'DROP TABLE IF EXISTS .".$preserved_data.".;' |sed 's/CREATE TABLE .".$preserved_data."./CREATE TABLE IF NOT EXISTS `".$preserved_data."`/g' |grep -v 'INSERT INTO .".$preserved_data.".' ";
    }
    $message = "Dumped the database to $file with minimal filtering.";
    break;

  default:
    foreach($tables_filtered as $filtered_data) {
      $filter .= "|grep -v 'INSERT INTO .".$filtered_data.".' ";
    }
    foreach($tables_preserved_full as $preserved_data) {
      $filter .= "|grep -v 'DROP TABLE IF EXISTS .".$preserved_data.".;' |sed 's/CREATE TABLE .".$preserved_data.". (/CREATE TABLE IF NOT EXISTS `".$preserved_data."` (/g' |grep -v 'INSERT INTO .".$preserved_data.". VALUES' ";
    }
    $message = "Dumped the database to $file with full filtering.";
    break;
}

$dump_options = "--skip-opt --add-drop-table --add-locks --create-options --quick --lock-tables --set-charset --disable-keys --order-by-primary --comments=FALSE --default-character-set=utf8 --hex-blob";
exec("mysqldump $dump_options $db_connection_settings $filter > $file_path/".$file);
print("\n$message\n\n");