#!/usr/local/bin/php
<?php
require('db_settings.inc');

/**
 * Performs an unmanipulated restore of the development database
 */

exec($path."dbscripts/erase_dev_database");
exec("mysql $db_connection_settings < ".$path."dbscripts/databases/development.sql");

print("Database restored.\n");